name       : cargo
version    : 0.22.0
release    : 8
source     :
    - https://github.com/rust-lang/cargo/archive/0.22.0.tar.gz : 6740e2f8d035a5a5246a12e84a141d37ad4c2b826355aff497e6f1fcfb637aef
license    :
    - Apache-2.0
    - MIT
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - BSD-3-Clause
component  : programming
summary    : The Rust package manager
description: |
    Cargo is a tool that allows Rust projects to declare their various
    dependencies and ensure that you'll always get a repeatable build.
networking : yes
builddeps  :
    - pkgconfig(libssl)
    - cargo
    - git       # check
    - rust
rundeps    :
    - rust
build      : |
    cargo build --release
    sh src/ci/dox.sh
install    : |
    cargo install --root=$installdir/usr
    rm $installdir/usr/.crates.toml

    install -Dm 00644 src/etc/cargo.bashcomp.sh $installdir/usr/share/bash-completion/completions.d/cargo.bashcomp.sh
    install -Dm 00644 src/etc/_cargo $installdir/usr/share/zsh/site-functions/_cargo
    install -Dm 00644 src/etc/man/cargo*.1 -t $installdir/usr/share/man/man1
    install -dm 00755 $installdir/usr/share/doc/cargo/html
    cp -a target/doc $installdir/usr/share/doc/cargo/html
check      : |
    CFG_DISABLE_CROSS_TESTS=1 cargo test --no-fail-fast
