name       : cargo
version    : 0.26.0
release    : 11
source     :
    - https://static.rust-lang.org/dist/rustc-1.25.0-src.tar.gz : eef63a0aeea5147930a366aee78cbde248bb6e5c6868801bdf34849152965d2d
license    :
    - Apache-2.0
    - MIT
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - BSD-3-Clause
component  : programming
summary    : The Rust package manager
description: |
    Cargo is a tool that allows Rust projects to declare their various
    dependencies and ensure that you'll always get a repeatable build.
networking : yes
builddeps  :
    - pkgconfig(libssl)
    - cargo
    - rust
    - mdbook
rundeps    :
    - rust
build      : |
    cd src/tools/cargo
    cargo build %JOBS% --release
install    : |
    cd src/tools/cargo
    cargo install %JOBS% --root=$installdir/usr
    rm $installdir/usr/.crates.toml

    install -Dm 00644 src/etc/cargo.bashcomp.sh $installdir/usr/share/bash-completion/completions/cargo
    install -Dm 00644 src/etc/_cargo $installdir/usr/share/zsh/site-functions/_cargo
    install -Dm 00644 src/etc/man/cargo*.1 -t $installdir/usr/share/man/man1
    install -dm 00755 $installdir/usr/share/doc/cargo/html
    mdbook build --no-create --dest-dir $installdir/usr/share/doc/cargo/html src/doc
