name       : cargo
version    : 0.32.0
release    : 15
source     :
    - https://static.rust-lang.org/dist/rustc-1.31.0-src.tar.gz : 9ad54dc0baf1db5fc6a79d54e71c439c82aff85cd96778978456f2958211ef06
license    :
    - Apache-2.0
    - MIT
    - GPL-2.0-or-later
    - BSD-4-Clause
    - OpenSSL
    - BSD-3-Clause
component  : programming
summary    : The Rust package manager
description: |
    Cargo is a tool that allows Rust projects to declare their various
    dependencies and ensure that you'll always get a repeatable build.
networking : yes
builddeps  :
    - pkgconfig(libssl)
    - cargo
    - rust
    - mdbook
rundeps    :
    - rust
build      : |
    %patch -p1 < $pkgfiles/0001-cargo-clipy-edition.patch
    cd src/tools/cargo
    cargo build %JOBS% --release
install    : |
    cd src/tools/cargo
    cargo install %JOBS% --root=$installdir/usr
    rm $installdir/usr/.crates.toml

    install -Dm00644 src/etc/cargo.bashcomp.sh $installdir/usr/share/bash-completion/completions/cargo
    install -Dm00644 src/etc/_cargo $installdir/usr/share/zsh/site-functions/_cargo
    install -Dm00644 src/etc/man/cargo*.1 -t $installdir/usr/share/man/man1
    install -dm00755 $installdir/usr/share/doc/cargo/html
    mdbook build --dest-dir $installdir/usr/share/doc/cargo/html src/doc